// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3yE3kvg2dE75hax_yWqJjxLTCLa8_2qo',
    appId: '1:989741872396:web:4de3decc921d479a0c8529',
    messagingSenderId: '989741872396',
    projectId: 'szakdolgozat-app',
    authDomain: 'szakdolgozat-app.firebaseapp.com',
    storageBucket: 'szakdolgozat-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADNN0fG9AwngfMRB7x2Ly49zAvc_aE2BQ',
    appId: '1:989741872396:android:8538321fd4f40c440c8529',
    messagingSenderId: '989741872396',
    projectId: 'szakdolgozat-app',
    storageBucket: 'szakdolgozat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDopCw8iwPvO7u17h2-IAPhtGEhUiVNPrQ',
    appId: '1:989741872396:ios:33c0c64f13e5016d0c8529',
    messagingSenderId: '989741872396',
    projectId: 'szakdolgozat-app',
    storageBucket: 'szakdolgozat-app.appspot.com',
    androidClientId: '989741872396-ja32d1t4bpbkaeq2n7lcreocnatfq5tq.apps.googleusercontent.com',
    iosClientId: '989741872396-0fqialhm0s4kjtiafjc60mdaolmhk9u2.apps.googleusercontent.com',
    iosBundleId: 'com.example.szakdolgozatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDopCw8iwPvO7u17h2-IAPhtGEhUiVNPrQ',
    appId: '1:989741872396:ios:33c0c64f13e5016d0c8529',
    messagingSenderId: '989741872396',
    projectId: 'szakdolgozat-app',
    storageBucket: 'szakdolgozat-app.appspot.com',
    androidClientId: '989741872396-ja32d1t4bpbkaeq2n7lcreocnatfq5tq.apps.googleusercontent.com',
    iosClientId: '989741872396-0fqialhm0s4kjtiafjc60mdaolmhk9u2.apps.googleusercontent.com',
    iosBundleId: 'com.example.szakdolgozatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3yE3kvg2dE75hax_yWqJjxLTCLa8_2qo',
    appId: '1:989741872396:web:d79ee2c672dd4b8e0c8529',
    messagingSenderId: '989741872396',
    projectId: 'szakdolgozat-app',
    authDomain: 'szakdolgozat-app.firebaseapp.com',
    storageBucket: 'szakdolgozat-app.appspot.com',
  );

}